---
title: "STA 237 Final Project"
author: "Yutian Yang"
date: "11/20/2021"
output: html_document
---

```{r}
infection <- read.csv("C:/Users/charl/Downloads/owid-covid-data.csv")
vaccination <- read.csv("C:/Users/charl/Downloads/covid-vaccination-policy.csv")

library(tidyverse)
```

```{r}
colnames(infection)[1] = c("Code")
colnames(infection)[4] = c("Day")

covid <-
infection %>%
  right_join(vaccination,by = c("Code","Day"))
```

```{r}
covid_north <-
  covid %>% 
  filter(continent %in% c("Asia","Europe","North America","Africa"))
```
```{r}
covid_north$Day = as.Date(covid_north$Day)

no_vaccination <-
covid_north %>%
  select(location,Day,vaccination_policy) %>%
  group_by(location) %>%
  filter(Day > "2021-3-1") %>%
  filter(vaccination_policy == 0) %>%
  distinct(location)

covid_north <-
  covid_north %>%
  filter(!(location %in% no_vaccination$location))

covid_north <-
  covid_north %>%
  filter(total_tests_per_thousand >= 10) %>%
  filter(total_vaccinations > 0)
  

```

```{r}
covid_north %>%
  #select()
  group_by(location) %>%
  count(NA) %>%
  arrange(desc(n))

NA_list = c("Latvia","Slovenia","Liechtenstein","Estonia","Lithuania","Slovakia","Malta","Saudi Arabia","Sri Lanka","Guatemala","Bahrain")

covid_north <-
  covid_north %>%
  filter(!(location %in% NA_list))
```

```{r}
#filtering out usa data with selected variables
covid_usa <-
  covid_north %>%
  select(c("location","Day","new_cases_per_million","new_tests_per_thousand","total_vaccinations","vaccination_policy")) %>%
  filter(location == "United States")
```

```{r}
library(forecast)

ts_covid_usa = ts(covid_usa$new_cases_per_million,frequency = 7)


ts_covid_usa_train = ts_covid_usa[1:290]
ts_covid_usa_test = ts_covid_usa[291:320]
plot(covid_usa$Day,                             
     ts_covid_usa,
     type = "l",
     xlab = "Date",
     ylab = "new cases per million",
     main = "ts coivd usa")
```





```{r}
fit = lm(new_cases_per_million~new_tests_per_thousand,data = covid_usa)
summary(fit)

#Taking out new tests rate effect on new cases rate

error_tests_rate = residuals(fit)

new_covid_usa <-
  covid_usa %>% mutate("error_tests_rate" = error_tests_rate)

#deseasonalized
new_covid_usa$error_tests_rate[8:320] = error_tests_rate %>% diff(7)
```


```{r}
# ARIMA as a special case of the ARIMAX intercept
regression_model = lm(error_tests_rate~1, data = new_covid_usa[8:290,]) 
summary(regression_model)
anova(regression_model)

error = residuals(regression_model)
ts_error = ts(error)

#ARIMA on error

error_model = auto.arima(ts_error)
summary(error_model)

checkresiduals(error_model)

#goodness of fit
regression_prediction = predict(regression_model)

final_prediction = regression_prediction + error

#restore final prediction
restore_final_prediction = c()
  
restore_final_prediction[1:7] = covid_usa$new_cases_per_million[1:7]

for (i in 8:290) {
  restore_final_prediction[i] = restore_final_prediction[i-7] + final_prediction[i] 
}



plot(covid_usa$Day[1:290],                              # Draw first time series
     covid_usa$new_cases_per_million[1:290],
     type = "l",
     xlab = "Date",
     ylab = "Prediction vs. Acutal")
lines(covid_usa$Day[1:290],                             # Draw second time series
      restore_final_prediction,
      type = "l",
      col = 3)
legend(x = "topright",legend=c("actual", "prediction"),
       col=c("black", "red"), lty=1, cex=0.5)
```


```{r}
#model prediction
regression_prediction = predict(regression_model, newdata = new_covid_usa[291:320,])
error_forecast =  predict(error_model, n.ahead = 30)$pred

final_prediction = regression_prediction + error_forecast

#restore final prediction
restore_final_prediction = c()
  
restore_final_prediction[1:7] = covid_usa$new_cases_per_million[284:290] + final_prediction[1:7]

for (i in 8:30) {
  restore_final_prediction[i] = restore_final_prediction[i-7] + final_prediction[i] 
}

#compare prediction and actual
compare_table = data.frame(final_prediction,covid_usa$new_cases_per_million[291:320])
colnames(compare_table) = c("predict","actual")

plot(covid_usa$Day[291:320],                              # Draw first time series
     covid_usa$new_cases_per_million[291:320],
     type = "l",
     xlab = "Date",
     ylab = "Prediction vs. Acutal")
lines(covid_usa$Day[291:320],                             # Draw second time series
      restore_final_prediction,
      type = "l",
      col = 3)
legend(x = "topright",legend=c("actual", "prediction"),
       col=c("black", "red"), lty=1, cex=0.5)
```


```{r}
#ARIMAX model
regression_model = lm(error_tests_rate~as.factor(vaccination_policy), data = new_covid_usa[8:290,]) 
summary(regression_model)
anova(regression_model)

error = residuals(regression_model)
ts_error = ts(error)

#ARIMA on error

error_model = auto.arima(ts_error)
summary(error_model)

checkresiduals(error_model)

#goodness of fit
regression_prediction = predict(regression_model)

final_prediction = regression_prediction + error

#restore final prediction
restore_final_prediction = c()
  
restore_final_prediction[1:7] = covid_usa$new_cases_per_million[1:7]

for (i in 8:290) {
  restore_final_prediction[i] = restore_final_prediction[i-7] + final_prediction[i] 
}



plot(covid_usa$Day[1:290],                              # Draw first time series
     covid_usa$new_cases_per_million[1:290],
     type = "l",
     xlab = "Date",
     ylab = "Prediction vs. Acutal")
lines(covid_usa$Day[1:290],                             # Draw second time series
      restore_final_prediction,
      type = "l",
      col = 3)
legend(x = "topright",legend=c("actual", "prediction"),
       col=c("black", "red"), lty=1, cex=0.5)
```


```{r}
#model prediction and forecast on the error term
regression_prediction = predict(regression_model, newdata = new_covid_usa[291:320,])
error_forecast =  predict(error_model, n.ahead = 30)$pred


final_prediction = regression_prediction + error_forecast

#restore final prediction
restore_final_prediction = c()
  
restore_final_prediction[1:7] = covid_usa$new_cases_per_million[284:290] + final_prediction[1:7]

for (i in 8:30) {
  restore_final_prediction[i] = restore_final_prediction[i-7] + final_prediction[i] 
}

#compare prediction and actual


compare_table = data.frame(restore_final_prediction,covid_usa$new_cases_per_million[291:320])
colnames(compare_table) = c("predict","actual")

plot(covid_usa$Day[291:320],                              # Draw first time series
     covid_usa$new_cases_per_million[291:320],
     type = "l",
     xlab = "Date",
     ylab = "Prediction vs. Acutal")
lines(covid_usa$Day[291:320],                             # Draw second time series
      restore_final_prediction,
      type = "l",
      col = 3)
legend(x = "topright",legend=c("actual", "prediction"),
       col=c("black", "red"), lty=1, cex=0.5)

head(compare_table)
```


```{r}
#ARIMAX method 2

library(TSA)

method_2 = arimax(ts_covid_usa[1:290],order = c(5,2,3),xreg = covid_usa$vaccination_policy[1:290])

final_model_prediction_2 = predict(method_2, n.ahead = 30,newxreg = covid_usa$vaccination_policy[291:320])


plot(covid_usa$Day[291:320],                              # Draw first time series
     covid_usa$new_cases_per_million[291:320],
     type = "l",
     xlab = "Date",
     ylab = "Prediction vs. Acutal")
lines(covid_usa$Day[291:320],                             # Draw second time series
      final_model_prediction_2$pred,
      type = "l",
      col = 3)
legend(x = "topright",legend=c("actual", "prediction"),
       col=c("black", "red"), lty=1, cex=0.5)



compare_table_2 = data.frame( final_model_prediction_2$pred,covid_usa$new_cases_per_million[291:320])
colnames(compare_table_2) = c("predict","actual")
head(compare_table_2)
```



