---
title: "STA 237"
author: "Yutian Yang"
date: "11/11/2021"
output: html_document
---

```{r}
infection <- read.csv("C:/Users/charl/Downloads/owid-covid-data.csv")
vaccination <- read.csv("C:/Users/charl/Downloads/covid-vaccination-policy.csv")

library(tidyverse)
```

```{r}
colnames(infection)[1] = c("Code")
colnames(infection)[4] = c("Day")

covid <-
infection %>%
  right_join(vaccination,by = c("Code","Day"))
```

```{r}
covid_north <-
  covid %>% 
  filter(continent %in% c("Asia","Europe","North America","Africa"))
```
```{r}
covid_north$Day = as.Date(covid_north$Day)

no_vaccination <-
covid_north %>%
  select(location,Day,vaccination_policy) %>%
  group_by(location) %>%
  filter(Day > "2021-3-1") %>%
  filter(vaccination_policy == 0) %>%
  distinct(location)

covid_north <-
  covid_north %>%
  filter(!(location %in% no_vaccination$location))

covid_north <-
  covid_north %>%
  filter(total_tests_per_thousand >= 10) %>%
  filter(total_vaccinations > 0)
  

```

```{r}
covid_north %>%
  #select()
  group_by(location) %>%
  count(NA) %>%
  arrange(desc(n))

NA_list = c("Latvia","Slovenia","Liechtenstein","Estonia","Lithuania","Slovakia","Malta","Saudi Arabia","Sri Lanka","Guatemala","Bahrain")

covid_north <-
  covid_north %>%
  filter(!(location %in% NA_list))
```

```{r}
#filtering out usa data with selected variables
covid_usa <-
  covid_north %>%
  select(c("location","Day","new_cases_per_million","new_tests_per_thousand","total_vaccinations","vaccination_policy")) %>%
  filter(location == "United States")
```

```{r}
library(forecast)

ts_covid_usa = ts(covid_usa$new_cases_per_million,frequency = 7)


ts_covid_usa_train = ts_covid_usa[1:290]
ts_covid_usa_test = ts_covid_usa[291:320]
plot(covid_usa$Day,                              # Draw first time series
     ts_covid_usa,
     type = "l",
     xlab = "Date",
     ylab = "new cases per million",
     main = "ts coivd usa")
```

```{r}
#detrend & deseasonal (not recommend)
# model: Xt = Mt + St + Zt

trend = decompose(ts_covid_usa)$trend
seasonal = decompose(ts_covid_usa)$seasonal

ts_covid_usa_station = ts_covid_usa - trend - seasonal
ts_covid_usa_station_train = ts_covid_usa_station[1:290]
ts_covid_usa_station_test = ts_covid_usa_station[291:320]

plot(covid_usa$Day,                              # Draw first time series
     ts_covid_usa_station,
     type = "l",
     xlab = "Date",
     ylab = "detrend(new cases per million)",
     main = "ts coivd usa")

#ARIMA
fit = auto.arima(ts_covid_usa_station_train)

summary(fit)

checkresiduals(fit)
```
```{r}
#Forecast
prediction = predict(fit,n.ahead = 30)$pred


plot(covid_usa$Day[291:320],                              # Draw first time series
     ts_covid_usa_station[291:320],
     type = "l",
     xlab = "Date",
     ylab = "Prediction vs. Acutal")
lines(covid_usa$Day[291:320],                             # Draw second time series
      prediction,
      type = "l",
      col = 3)
legend(x = "topright",legend=c("actual", "prediction"),
       col=c("black", "red"), lty=1, cex=0.5)



autoplot(fit)
#This means the model is causal and invertible

# https://otexts.com/fpp2/arima-r.html
```

```{r}
#Detrend 2
# model: (1-B^7)Yt

detrend_ts_covid_usa_train = ts_covid_usa_train %>% diff(7)
ts_covid_usa_train %>% diff(7) %>% ggtsdisplay(main="")


#how to restore diff back to original value (easier for interpretation)
#restore = c()
#restore[1:7] = ts_covid_usa_train[1:7]
#for (i in 8:length(ts_covid_usa_train)) {
#  restore[i] = ts_covid_usa_train[i-7] + detrend_ts_covid_usa_train[i-7]
#  
#}



#ARIMA
fit = auto.arima(detrend_ts_covid_usa_train)
summary(fit)

checkresiduals(fit)
```
```{r}
#Forecast
prediction = predict(fit,n.ahead = 30)$pred
restore = c()
restore[1:7] = ts_covid_usa_train[284:290] + prediction[1:7]
for (i in 8:30) {
  restore[i] = restore[i-7] + prediction[i]
  
}

plot(covid_usa$Day[291:320],                              # Draw first time series
     covid_usa$new_cases_per_million[291:320],
     type = "l",
     xlab = "Date",
     ylab = "Prediction vs. Acutal")
lines(covid_usa$Day[291:320],                             # Draw second time series
      restore,
      type = "l",
      col = 3)
legend(x = "topright",legend=c("actual", "prediction"),
       col=c("black", "red"), lty=1, cex=0.5)


autoplot(fit)
#This means the model is causal and invertible

# https://otexts.com/fpp2/arima-r.html
```


```{r}
#ARIMAX method 1

regression_model = lm(new_cases_per_million~as.factor(vaccination_policy), data = covid_usa[1:290,]) 
summary(regression_model)

error = residuals(regression_model)
ts_error = ts(error)

plot(covid_usa$Day[1:290],                              # Draw first time series
     ts_error,
     type = "l",
     xlab = "Date",
     ylab = "residuals",
     main = "ts coivd usa")


detrend_ts_error = ts_error %>% diff(7)
ts_error %>% diff(7) %>% ggtsdisplay(main="")

#ARIMA on error
error_model = auto.arima(detrend_ts_error)
summary(error_model)

checkresiduals(error_model)
```


```{r}
# combine with regression model

# final_model = regression_model + error_model

regression_prediction = predict(regression_model, newdata = covid_usa[291:320,])
error_diff_forecast =  predict(error_model, n.ahead = 30)$pred

restore_error_forecast = c()
restore_error_forecast[1:7] = ts_error[284:290] + error_diff_forecast[1:7]
for (i in 8:30) {
  restore_error_forecast[i] = restore_error_forecast[i-7] + error_diff_forecast[i]
  
}




final_model_prediction = regression_prediction + restore_error_forecast

compare_table = data.frame( final_model_prediction,covid_usa$new_cases_per_million[291:320])
colnames(compare_table) = c("predict","actual")

plot(covid_usa$Day[291:320],                              # Draw first time series
     covid_usa$new_cases_per_million[291:320],
     type = "l",
     xlab = "Date",
     ylab = "Prediction vs. Acutal")
lines(covid_usa$Day[291:320],                             # Draw second time series
      final_model_prediction,
      type = "l",
      col = 3)
legend(x = "topright",legend=c("actual", "prediction"),
       col=c("black", "red"), lty=1, cex=0.5)

head(compare_table)
```

```{r}
#ARIMAX method 2

library(TSA)

method_2 = arimax(ts_covid_usa[1:290],order = c(3,0,5),xreg = covid_usa$vaccination_policy[1:290])

final_model_prediction_2 = predict(method_2, n.ahead = 30,newxreg = covid_usa$vaccination_policy[291:320])


plot(covid_usa$Day[291:320],                              # Draw first time series
     covid_usa$new_cases_per_million[291:320],
     type = "l",
     xlab = "Date",
     ylab = "Prediction vs. Acutal")
lines(covid_usa$Day[291:320],                             # Draw second time series
      final_model_prediction_2$pred,
      type = "l",
      col = 3)
legend(x = "topright",legend=c("actual", "prediction"),
       col=c("black", "red"), lty=1, cex=0.5)



compare_table_2 = data.frame( final_model_prediction_2$pred,covid_usa$new_cases_per_million[291:320])
colnames(compare_table_2) = c("predict","actual")
head(compare_table_2)
```



